Repository cphainmerakaam/CPCODES-Hacktoberfest2022, pull requests merged in 2021-10, with the labels that each got.

#1 Create rainwater_harvesting
  Leetcode/rainwater_harvesting
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#2 Created bfs_rotten_oranges.cpp
  Leetcode/bfs_rotten_oranges.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#3 CodeChef- Decreasing String
  CodeChef/DECSTR.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#4 CodeChef - The Best Box
  CodeChef/J7.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#5 CodeChef - Little Elephant and Bombs
  CodeChef/LEBOMBS.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#9 Added BENCHP.cpp
  CodeChef/BENCHP.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2021

#10 Create sqrt(x).cpp
  Leetcode/sqrt(x).cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#11 Create validpsqr.cpp
  Leetcode/validpsqr.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#8 CodeChef Paying up
  CodeChef/A1.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#12 Create addString.cpp
  Leetcode/addString.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#13 Create plusone.cpp
  Leetcode/plusone.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#7 Reverse Nodes in k-Group
  Leetcode/reverse_nodes_in_k-group.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#27 Create Median_of_Two_Sorted_Arrays.cpp
  Leetcode/Median_of_Two_Sorted_Arrays.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#15 Create Median-of-two-sorted-arrays.cpp
  Leetcode/Median-of-two-sorted-arrays.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#43 Create Sudoku-Solver.cpp
  Leetcode/Sudoku-Solver.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#16 Leetcode_1448
  Leetcode/Array-partition-1
  Leetcode/countGoodNodes
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#17 Alternating subarray prefix problem solution
  CodeChef/ALTARAY.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#19 New code sliding_window_max_of_all_subarrays.cpp
  Leetcode/sliding_window_max_of_all_subarrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#21 added code for distinct subsequences
  Leetcode/distinct_subsequences.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#22 Added Code for: Max Path Sum in Binary Tree
  Leetcode/MaxPathSumBT.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#23 Birthday Gifts - Codechef
  CodeChef/TWINGFT.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#24 Create RCBPLAY.cpp
  CodeChef/RCBPLAY.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#31 Number of Pairs of Strings With Concatenation Equal to Target
  Leetcode/NumberOfPairsOfStringsWithConcatenationEqualToTarget.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#32 Created validparenthesis.cpp
  Leetcode/validparenthesis.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#33 CodeChef - Even Game
  CodeChef/EVENGAME.cpp
  CodeChef/PRFXGD.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#34 Added Code for First Missing Positive Integer
  Leetcode/FirstMissingPositive.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#44 Add The solution of MEX-OR problem
  CodeChef/mex-or.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2021
